name: 重用工作流测试

on:
  workflow_dispatch: {}

jobs:
  call_reusable:
    name: 输入内容
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.repository }}/.github/actions/my-action.yml@main
        with:
          username: 'danyow'
