name: 重用工作流测试

on:
  workflow_dispatch: {}
  release:
    type:
      - published

jobs:
  call_reusable:
    uses: danyow/github-action/.github/workflows/my-action.yml@main
    with:
      username: ${{ github.event.action == 'published' }}
