on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    name: 任务
    runs-on: ubuntu-latest
    steps:
      - name: 打印
        run: |
          echo 输入是 ${{ inputs.username }} 
          echo ${{ github.event.action }}
